source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'AppLovinSDK', '13.1.0'
  pod 'DIOSDK', '4.3.1'
  pod 'AppLovin-DIO-Adapter', '4.3.1'
end
use_frameworks! :linkage => :static
